export const JourneyData = [
  {
    imageSrc: "/JourneyPic/uwmadison.png",
    imageAlt: "UW Madison",
    techStack: ["Data Analysis", "Decision Making", "Data Visualization", "Database Management", "Project Management", "Product Management"],
    // hoverText1: "Swapnapurti (NGO)",
    // hoverText2: "Swapnapurti (NGO)",
    date: "September 2023 - Present",
    styles: "",
    projectName: "Master's in Information Science",
    content: [
      "I am currently pursuing a Master's degree in Information Science, where I am exploring the dynamic and ever-evolving field of information management, technology, and data analysis to gain a deep understanding of how information shapes our world and influences decision-making processes.",
    ],
    // liveLink: "https://www.swapnapurti.org/",
    // codeLink: "",
  },
  {
    imageSrc: "/JourneyPic/cerence.jpeg",
    imageAlt: "Cerence",
    techStack: ["Automotive", "AI", "Data"],
    // hoverText1: "React",
    // hoverText2: "Events",
    date: "Feb 2021 - Jun 2023",
    styles: "",
    projectName: "Cerence",
    content: [
      "At Cerence, contributed to the forefront of voice recognition technology, specializing in developing innovative solutions for automotive and virtual assistants, all aimed at enhancing user experiences through cutting-edge technology.Developed an intuitive and user-friendly app interface facilitating seamless navigation across multiple sections and features.",
    ],
    // liveLink: "",
    // codeLink: "https://github.com/bakliwalvaibhav1/react-navigation-v6",
  },
  {
    imageSrc: "/JourneyPic/amazatic.png",
    imageAlt: "Amazatic",
    techStack: ["Web Devlopment"],
    // hoverText1: "React",
    // hoverText2: "Events",
    date: "Mar 2019 - Jun 2019",
    styles: "",
    projectName: "Amazatic",
    content: [
      "Designed and developed various website pages and web apps, ensuring functionality, user satisfaction, and seamless cross-browser compatibility across Chrome, Firefox, Safari, and Edge for a consistent user experience.",
    ],
    // liveLink: "",
    // codeLink: "https://github.com/bakliwalvaibhav1/react-navigation-v6",
  },
  {
    imageSrc: "/JourneyPic/mit.jpeg",
    imageAlt: "MIT",
    techStack: ["Electronics", "Robotics", "Programming"],
    // hoverText1: "Facebook",
    // hoverText2: "Login",
    date: "June 2016 - May 2020",
    projectName: "MIT, Bachelor's of Engineering",
    content: [
      "I have successfully completed my Bachelor's degree in Electronics and Telecommunications, which equipped me with a solid foundation in the fields of electronics, telecommunications, and signal processing.",
    ],
    // liveLink: "",
    // codeLink: "https://github.com/bakliwalvaibhav1/Pokeverse",
  },
];
