export const ProjectData = [
  {
    imageSrc: "/ProjectPic/swapnapurti_logo.png",
    imageAlt: "Swapnapurti (NGO)",
    techStack: ["HTML", "CSS", "Bootstrap", "JavaScript", "PHP", "MySQL", "PayU payment gateway"],
    // hoverText1: "Swapnapurti (NGO)",
    // hoverText2: "Swapnapurti (NGO)",
    styles: "",
    projectName: "Swapnapurti (NGO)",
    content: [
      "Designed and developed a content management system (CMS) which enables the volunteers to manage their events, attendance, registrations, etc. The admin can track the record of every volunteer and manage the team.",
      "Created a payment gateway for accepting donations/membership fees.",
    ],
    liveLink: "https://www.swapnapurti.org/",
    codeLink: "",
  },
  // {
  //   imageSrc: "https://images.unsplash.com/photo-1554672408-758865e7274a?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   imageAlt: "UberEats_Clone",
  //   techStack: ["Typescript", "React", "React Router", "Redux", "Firebase", "TailwindCSS"],
  //   hoverText1: "Uber",
  //   hoverText2: "Eats Clone",
  //   styles: "",
  //   projectName: "Uber Eats Clone",
  //   content: [
  //     "Focused on gaining hands-on experience with TypeScript, Firebase and React libraries through project development.",
  //     "Implemented restaurant listings with menus for multiple stores, including special offers, favorite store selection, and detailed order history.",
  //   ],
  //   liveLink: "https://reactiverse-2842e.web.app/",
  //   codeLink: "https://github.com/MandeepPaul/Uber-Eats-Clone",
  // },
  {
    imageSrc: "/ProjectPic/react_navigation.png",
    imageAlt: "React Navigation",
    techStack: ["React Native", "React Navigation", "Javascript", "Expo"],
    // hoverText1: "React",
    // hoverText2: "Events",
    projectName: "React Navigation",
    content: [
      "Developed an intuitive and user-friendly app interface facilitating seamless navigation across multiple sections and features.",
      "Implemented a robust navigation system using React Navigation, ensuring smooth transitions and interactions for enhanced user experience.",
    ],
    liveLink: "",
    codeLink: "https://github.com/bakliwalvaibhav1/react-navigation-v6",
  },
  {
    imageSrc: "/ProjectPic/pokeverse.jpeg",
    imageAlt: "Pokéverse",
    techStack: ["Angular", "Ionic", "Typescript", "API"],
    // hoverText1: "Facebook",
    // hoverText2: "Login",
    projectName: "Pokéverse",
    content: [
      "Crafted an engaging Pokédex application with Ionic and Angular, enhancing the user experience through gamified elements.",
      "Infused gamified features seamlessly into the Pokédex app, transforming the exploration of Pokémon data into an interactive and enjoyable experience.",
    ],
    liveLink: "",
    codeLink: "https://github.com/bakliwalvaibhav1/Pokeverse",
  },

  {
    imageSrc: "/ProjectPic/virtue_logo.png",
    imageAlt: "Virtue Electronics",
    techStack: ["HTML", "CSS", "Bootstrap", "JavaScript", "PHP", "MySQL"],
    // hoverText1: "Stateless",
    // hoverText2: "Authentication",
    projectName: "Virtue Electronics",
    content: ["Designed and developed an Inventory Management System where users can keep a track of the inventory, purchase, sale and other activities of the organization."],
    liveLink: "https://www.virtueelectronics.com/",
    codeLink: "",
  },
  // {
  //   imageSrc: "https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  //   imageAlt: "Portfolio Website",
  //   techStack: ["Next.js", "TailwindCSS", "Framer Motion"],
  //   hoverText1: "My",
  //   hoverText2: "Portfolio",
  //   projectName: "Portfolio Website",
  //   content: ["Built my portfolio using Next.js 14, adopting the app router approach."],
  //   liveLink: "",
  //   codeLink: "https://github.com/MandeepPaul/Portfolio",
  // },
];
